//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHORROS_BIT_TRAS
    {
        public int cod_cliente { get; set; }
        public int num_contrato { get; set; }
        public string accion { get; set; }
        public System.DateTime fecIngreso { get; set; }
        public string codUsuario { get; set; }
    }
}
