//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulos
    {
        public Modulos()
        {
            this.SubOpciones = new HashSet<SubOpciones>();
        }
    
        public int IdModulo { get; set; }
        public string DesModulo { get; set; }
        public int EstModulo { get; set; }
    
        public virtual ICollection<SubOpciones> SubOpciones { get; set; }
    }
}
