//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantallas
    {
        public int IdSubOp { get; set; }
        public int IdPantalla { get; set; }
        public string DesPantalla { get; set; }
        public string NomPantalla { get; set; }
        public int EstPantalla { get; set; }
    
        public virtual SubOpciones SubOpciones { get; set; }
    }
}
