//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int IdUsuario { get; set; }
        public int IdObjeto { get; set; }
        public int Visible { get; set; }
        public int Lectura { get; set; }
        public int Escritura { get; set; }
        public int Borrado { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
