//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubOpciones
    {
        public SubOpciones()
        {
            this.Pantallas = new HashSet<Pantallas>();
        }
    
        public int IdModulo { get; set; }
        public int IdSubOp { get; set; }
        public string DesSubOp { get; set; }
        public string NomBoton { get; set; }
        public int EstSuubOp { get; set; }
        public Nullable<int> ImgIndex { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual ICollection<Pantallas> Pantallas { get; set; }
    }
}
